import React, {useEffect, useMemo, useState} from 'react';
import {createRoot} from 'react-dom/client';
import {ArrowRight, BarChart3, CalendarDays, Check, ChevronRight, Clock3, Download, LayoutDashboard, LogOut, Medal, Menu, Plus, Search, Settings, Sparkles, Trophy, Users, X, Zap} from 'lucide-react';
import './styles.css';
import './auth.css';
import './live.css';
import './setup.css';
import './registration.css';
import './schedule.css';
import {supabase} from './supabase';

type Event={id:number|string;name:string;category:string;venue:string;time:string;participants:number;status:'Upcoming'|'Live'|'Completed'};
const seedEvents:Event[]=[
 {id:1,name:'Mappilappattu',category:'Music',venue:'Main Stage',time:'09:30 AM',participants:18,status:'Live'},
 {id:2,name:'Digital Poster Design',category:'Digital Arts',venue:'Media Lab',time:'10:30 AM',participants:24,status:'Upcoming'},
 {id:3,name:'Arabic Calligraphy',category:'Fine Arts',venue:'Art Hall',time:'11:15 AM',participants:16,status:'Upcoming'},
 {id:4,name:'Group Debate',category:'Literary',venue:'Seminar Hall',time:'12:00 PM',participants:12,status:'Upcoming'},
 {id:5,name:'Mime',category:'Theatre',venue:'Open Stage',time:'02:00 PM',participants:8,status:'Upcoming'},
];
const teams=[{name:'Aster',score:680,color:'#ff6b35'},{name:'Nova',score:625,color:'#2774ff'},{name:'Solis',score:590,color:'#ffc928'},{name:'Orion',score:545,color:'#b7f34a'}];
const nav=[['Overview',LayoutDashboard],['Setup',Settings],['Events',CalendarDays],['Participants',Users],['Schedule',Clock3],['Results',Trophy],['Reports',BarChart3]] as const;

function Logo(){return <div className="logo"><span className="mark">K</span><span>KALA<b>TRACK</b></span></div>}
function Status({value}:{value:Event['status']}){return <span className={'status '+value.toLowerCase()}>{value==='Live'&&<i/>}{value}</span>}

function Landing({demo,login}:{demo:()=>void,login:()=>void}){
 return <div className="landing">
  <header><Logo/><nav><a href="#features">Features</a><a href="#events">Events</a><a href="#about">About</a></nav><button className="ghost" onClick={login}>Organizer login</button><button className="mobile"><Menu/></button></header>
  <main>
   <section className="hero"><div className="heroCopy"><div className="eyebrow"><Sparkles size={15}/> FEST MANAGEMENT, REIMAGINED</div><h1>Where every talent<br/><em>finds its stage.</em></h1><p>KalaTrack brings registrations, scheduling, judging and live results into one beautiful place—so you can focus on celebrating art.</p><div className="actions"><button className="primary" onClick={demo}>Explore demo <ArrowRight size={18}/></button><button className="link" onClick={demo}>View live results <ChevronRight size={18}/></button></div><div className="trust"><span><Check/> 60+ events</span><span><Check/> Real-time scores</span><span><Check/> Zero paperwork</span></div></div>
    <div className="poster"><div className="orb o1"/><div className="orb o2"/><span className="edition">KALA '26</span><div className="posterWords"><small>INTER-COLLEGE ARTS FEST</small><strong>CREATE<br/>PERFORM<br/><i>CELEBRATE.</i></strong><p>18—20 SEPTEMBER · CALICUT</p></div><div className="ticket"><span>ALL EVENTS</span><b>60+</b></div></div>
   </section>
   <section className="ticker"><span>LIVE NOW</span><b>Mappilappattu · Main Stage</b><i>18 participants</i><button onClick={demo}>Follow event <ArrowRight size={16}/></button></section>
   <section className="features" id="features"><div><small>ONE FEST. ONE PLATFORM.</small><h2>Everything behind the<br/>curtain, handled.</h2></div><div className="featureGrid">{[[Zap,'Instant registration','Students register in seconds. Organizers see every entry in one clean view.'],[CalendarDays,'Conflict-free schedule','Build stages and time slots without clashes or last-minute confusion.'],[Medal,'Transparent scoring','Judges score securely. Results calculate and publish automatically.']].map(([Icon,title,text]:any)=><article key={title}><Icon/><h3>{title}</h3><p>{text}</p><a onClick={demo}>Learn more <ArrowRight size={15}/></a></article>)}</div></section>
  </main><footer><Logo/><p>Celebrate Art. Organize Smart.</p><span>© 2026 KalaTrack</span></footer>
 </div>
}

function Dashboard({exit,festival=null,demo=false}:{exit:()=>void,festival?:any,demo?:boolean}){
 const [active,setActive]=useState('Overview'); const [events,setEvents]=useState<Event[]>(demo?seedEvents:[]); const [query,setQuery]=useState(''); const [modal,setModal]=useState(false); const [dataError,setDataError]=useState(''); const [eventCategories,setEventCategories]=useState<any[]>([]); const [eventVenues,setEventVenues]=useState<any[]>([]);
 const festName=demo?"Kala '26":festival?.name||'My Festival'; const start=demo?new Date('2026-09-18'):new Date(festival?.start_date+'T00:00:00'); const end=demo?new Date('2026-09-20'):new Date(festival?.end_date+'T00:00:00'); const dateText=`${start.toLocaleDateString('en',{month:'short',day:'numeric'})}–${end.toLocaleDateString('en',{month:'short',day:'numeric',year:'numeric'})}`;
 useEffect(()=>{if(demo||!festival)return;(async()=>{const [{data,error},{data:cats},{data:venues}]=await Promise.all([supabase.from('events').select('*,categories(name),venues(name),registrations(count)').eq('festival_id',festival.id).order('scheduled_start',{ascending:true}),supabase.from('categories').select('id,name').eq('festival_id',festival.id).order('name'),supabase.from('venues').select('id,name').eq('festival_id',festival.id).order('name')]);setEventCategories(cats||[]);setEventVenues(venues||[]);if(error)setDataError(error.message);else setEvents((data||[]).map((e:any)=>({id:e.id,name:e.name,category:e.categories?.name||'Unassigned',venue:e.venues?.name||'Unassigned',time:e.scheduled_start?new Date(e.scheduled_start).toLocaleString([],{month:'short',day:'numeric',hour:'2-digit',minute:'2-digit'}):'Not scheduled',participants:e.registrations?.[0]?.count||0,status:e.status==='live'?'Live':e.status==='completed'?'Completed':'Upcoming'})))})()},[festival,demo]);
 const shown=useMemo(()=>events.filter(e=>e.name.toLowerCase().includes(query.toLowerCase())),[events,query]);
 async function add(e:React.FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget);const categoryId=String(f.get('category_id')||'');const venueId=String(f.get('venue_id')||'');const scheduled=String(f.get('scheduled_start')||'');const category=eventCategories.find(x=>x.id===categoryId)?.name||String(f.get('category')||'Unassigned');const venue=eventVenues.find(x=>x.id===venueId)?.name||String(f.get('venue')||'Unassigned');const item:Event={id:Date.now(),name:String(f.get('name')),category,venue,time:scheduled?new Date(scheduled).toLocaleString([],{month:'short',day:'numeric',hour:'2-digit',minute:'2-digit'}):String(f.get('time')||'Not scheduled'),participants:0,status:'Upcoming'};if(demo){setEvents(v=>[...v,item]);setModal(false);return}const code=item.name.toUpperCase().replace(/[^A-Z0-9]+/g,'-').replace(/^-|-$/g,'')+'-'+Date.now().toString().slice(-4);const {data,error}=await supabase.from('events').insert({festival_id:festival.id,name:item.name,code,event_type:String(f.get('event_type')||'individual'),category_id:categoryId||null,venue_id:venueId||null,scheduled_start:scheduled?new Date(scheduled).toISOString():null,max_participants:Number(f.get('max_participants'))||null,status:'open'}).select().single();if(error){setDataError(error.message);return}setEvents(v=>[...v,{...item,id:data.id}]);setModal(false)}
 return <div className="app"><aside><Logo/><div className="festSelect"><span>ACTIVE FEST</span><b>{festName}</b><small>{dateText}</small></div><nav>{nav.map(([n,I])=><button className={active===n?'selected':''} onClick={()=>setActive(n)} key={n}><I/>{n}</button>)}</nav><div className="asideBottom"><button onClick={()=>setActive('Settings')}><Settings/>Settings</button><button onClick={exit}><LogOut/>{demo?'Exit demo':'Sign out'}</button><div className="user"><span>MS</span><div><b>Muhammed Shinas</b><small>Super Admin</small></div></div></div></aside>
 <section className="workspace"><div className="top"><div><small>{festName.toUpperCase()} / {active.toUpperCase()}</small><h1>{active}</h1></div><div className="topActions"><label><Search/><input placeholder="Search anything..."/></label><button className="primary" onClick={()=>setModal(true)}><Plus/> New event</button></div></div>{dataError&&<div className="authMessage">{dataError}</div>}
 {active==='Overview'?<><div className="welcome"><div><span>{demo?'DAY 01 · LIVE':'FESTIVAL WORKSPACE'}</span><h2>{demo?'Good morning, Shinas.':festName+' is ready.'}</h2><p>{demo?'The fest is moving beautifully. Here’s what needs your attention.':'Start by adding events, participants, venues and teams.'}</p></div><div className="bigDate"><b>{start.getDate()}</b><span>{start.toLocaleDateString('en',{month:'short'}).toUpperCase()}<br/><small>{start.toLocaleDateString('en',{weekday:'long'}).toUpperCase()}</small></span></div></div>
 <div className="stats">{(demo?[['Total events','64','+8 this week'],['Participants','1,248','92% verified'],['Completed','18','28% of events'],['Team leader','Aster','680 points']]:[['Total events',String(events.length),'Saved in Supabase'],['Event entries',String(events.reduce((total,event)=>total+event.participants,0)),'Approved registrations'],['Completed',String(events.filter(e=>e.status==='Completed').length),'Live calculation'],['Team leader','—','No results published']]).map((a,i)=><article key={a[0]}><span>{a[0]}</span><b className={'c'+i}>{a[1]}</b><small>{a[2]}</small></article>)}</div>
 <div className="dashGrid"><div className="panel"><div className="panelHead"><div><small>TODAY'S FLOW</small><h3>Event timeline</h3></div><button onClick={()=>setActive('Schedule')}>Full schedule <ArrowRight/></button></div><div className="timeline">{events.slice(0,4).map(e=><div key={e.id}><time>{e.time}</time><i className={e.status.toLowerCase()}/><section><b>{e.name}</b><small>{e.venue} · {e.participants} participants</small></section><Status value={e.status}/></div>)}</div></div>
 <div className="panel leaderboard"><div className="panelHead"><div><small>LIVE STANDINGS</small><h3>Team leaderboard</h3></div><Trophy/></div>{demo?teams.map((t,i)=><div className="team" key={t.name}><strong>{i+1}</strong><span style={{background:t.color}}>{t.name[0]}</span><section><b>{t.name}</b><div><i style={{width:(t.score/7)+'%',background:t.color}}/></div></section><em>{t.score}</em></div>):<div className="emptySmall"><Trophy/><b>No standings yet</b><span>Publish event results to calculate team points.</span></div>}<button onClick={()=>setActive('Results')}>View detailed results</button></div></div></>:<div className="panel pagePanel"><div className="panelHead"><div><small>FEST CONTROL</small><h3>{active} management</h3></div>{active==='Events'&&<button className="primary" onClick={()=>setModal(true)}><Plus/> Add event</button>}</div>{active==='Events'?<><div className="tableSearch"><Search/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Find an event"/></div>{shown.length?<table><thead><tr><th>Event</th><th>Category</th><th>Venue & time</th><th>Entries</th><th>Status</th></tr></thead><tbody>{shown.map(e=><tr key={e.id}><td><b>{e.name}</b></td><td>{e.category}</td><td>{e.venue}<small>{e.time}</small></td><td>{e.participants}</td><td><Status value={e.status}/></td></tr>)}</tbody></table>:<div className="emptySmall"><CalendarDays/><b>No events yet</b><span>Create the first event for {festName}.</span></div>}</>:<EmptyPage active={active}/>}</div>}
 </section>{modal&&<div className="modalBackdrop"><form className="modal eventForm" onSubmit={add}><button type="button" className="close" onClick={()=>setModal(false)}><X/></button><small>CREATE</small><h2>Add a new event</h2><p>Connect the event to your festival structure and schedule.</p><label>Event name<input required name="name" placeholder="e.g. Watercolour painting"/></label><div className="two"><label>Category<select name={demo?'category':'category_id'} required={!demo}>{demo?<><option>Fine Arts</option><option>Music</option><option>Literary</option></>:<><option value="">Select category</option>{eventCategories.map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</>}</select></label><label>Venue<select name={demo?'venue':'venue_id'} required={!demo}>{demo?<><option>Main Stage</option><option>Art Hall</option><option>Media Lab</option></>:<><option value="">Select venue</option>{eventVenues.map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</>}</select></label></div><div className="two"><label>Event type<select name="event_type"><option value="individual">Individual</option><option value="group">Group</option></select></label><label>Maximum entries<input name="max_participants" type="number" min="1" placeholder="Optional"/></label></div><label>{demo?'Time':'Scheduled date & time'}<input name={demo?'time':'scheduled_start'} type={demo?'time':'datetime-local'} required/></label>{!demo&&(!eventCategories.length||!eventVenues.length)&&<div className="authMessage">Create at least one category and venue from Setup before adding an event.</div>}<button className="primary" disabled={!demo&&(!eventCategories.length||!eventVenues.length)}>Create event <ArrowRight/></button></form></div>}</div>
}
function EmptyPage({active,festival,demo=false}:{active:string,festival?:any,demo?:boolean}){
 const [people,setPeople]=useState<any[]>(()=>JSON.parse(localStorage.getItem('kalatrack-people')||'null')||[{id:'KT-001',name:'Amina Fathima',team:'Aster',events:3,status:'Verified'},{id:'KT-002',name:'Rizwan Ali',team:'Nova',events:2,status:'Verified'},{id:'KT-003',name:'Fathima Nida',team:'Solis',events:4,status:'Pending'},{id:'KT-004',name:'Adil Rahman',team:'Orion',events:1,status:'Verified'}]);
 const [modal,setModal]=useState(false); const [notice,setNotice]=useState('');
 const [setupTab,setSetupTab]=useState<'teams'|'categories'|'venues'>('teams'); const [setupItems,setSetupItems]=useState<any[]>([]); const [setupFestival,setSetupFestival]=useState<any>(festival||null); const [setupOpen,setSetupOpen]=useState(false); const [setupError,setSetupError]=useState('');
 const [participantTeams,setParticipantTeams]=useState<any[]>([]); const [participantEvents,setParticipantEvents]=useState<any[]>([]); const [registering,setRegistering]=useState<any>(null); const [participantError,setParticipantError]=useState(''); const [scheduleEvents,setScheduleEvents]=useState<any[]>([]); const [scheduleDate,setScheduleDate]=useState(''); const [scheduleError,setScheduleError]=useState('');
 useEffect(()=>{if(demo)localStorage.setItem('kalatrack-people',JSON.stringify(people))},[people,demo]);
 useEffect(()=>{if(active!=='Setup'||demo)return;(async()=>{let fest=setupFestival;if(!fest){const {data}=await supabase.from('festivals').select('*').order('created_at',{ascending:true}).limit(1).maybeSingle();fest=data;setSetupFestival(data)}if(!fest)return;const {data,error}=await supabase.from(setupTab).select('*').eq('festival_id',fest.id).order('created_at',{ascending:true});if(error)setSetupError(error.message);else setSetupItems(data||[])})()},[active,setupTab,setupFestival,demo]);
 useEffect(()=>{if(active!=='Participants'||demo)return;(async()=>{let fest=setupFestival;if(!fest){const {data}=await supabase.from('festivals').select('*').order('created_at',{ascending:true}).limit(1).maybeSingle();fest=data;setSetupFestival(data)}if(!fest)return;const [{data:rows,error},{data:teamRows},{data:eventRows}]=await Promise.all([supabase.from('participants').select('id,admission_no,full_name,verification_status,team_id,teams(name),registrations(count)').eq('festival_id',fest.id).order('created_at',{ascending:true}),supabase.from('teams').select('id,name,color').eq('festival_id',fest.id).order('name'),supabase.from('events').select('id,name,event_type,status').eq('festival_id',fest.id).order('name')]);setParticipantTeams(teamRows||[]);setParticipantEvents(eventRows||[]);if(error)setParticipantError(error.message);else setPeople((rows||[]).map((p:any)=>({dbId:p.id,id:p.admission_no,name:p.full_name,team:p.teams?.name||'Unassigned',teamId:p.team_id,events:p.registrations?.[0]?.count||0,status:p.verification_status==='verified'?'Verified':p.verification_status==='rejected'?'Rejected':'Pending'})))})()},[active,demo,setupFestival]);
 useEffect(()=>{if(active!=='Schedule'||demo)return;(async()=>{let fest=setupFestival;if(!fest){const {data}=await supabase.from('festivals').select('*').order('created_at',{ascending:true}).limit(1).maybeSingle();fest=data;setSetupFestival(data)}if(!fest)return;if(!scheduleDate)setScheduleDate(fest.start_date);const {data,error}=await supabase.from('events').select('id,name,event_type,status,scheduled_start,scheduled_end,max_participants,venues(id,name),categories(name),registrations(count)').eq('festival_id',fest.id).order('scheduled_start',{ascending:true});if(error)setScheduleError(error.message);else setScheduleEvents(data||[])})()},[active,demo,setupFestival,scheduleDate]);
 const toast=(m:string)=>{setNotice(m);setTimeout(()=>setNotice(''),2000)};
 const scheduleDays=useMemo(()=>{if(!setupFestival)return[];const days=[];let d=new Date(setupFestival.start_date+'T00:00:00');const end=new Date(setupFestival.end_date+'T00:00:00');while(d<=end&&days.length<14){days.push(d.toISOString().slice(0,10));d=new Date(d.getTime()+86400000)}return days},[setupFestival]);
 const selectedScheduleEvents=scheduleEvents.filter(e=>e.scheduled_start?.slice(0,10)===scheduleDate); const scheduleVenues=Array.from(new Set(selectedScheduleEvents.map(e=>e.venues?.name||'Unassigned venue')));
 async function addParticipant(name:string,admissionNo:string,teamId:string){if(demo){const team=participantTeams.find(t=>t.id===teamId)?.name||'Aster';setPeople(v=>[...v,{id:admissionNo,name,team,teamId,events:0,status:'Pending'}]);setModal(false);return}if(!setupFestival)return;const {data,error}=await supabase.from('participants').insert({festival_id:setupFestival.id,full_name:name,admission_no:admissionNo,team_id:teamId||null,verification_status:'pending'}).select('id,admission_no,full_name,verification_status,team_id,teams(name)').single();if(error){setParticipantError(error.message);return}setPeople(v=>[...v,{dbId:data.id,id:data.admission_no,name:data.full_name,team:(data.teams as any)?.name||'Unassigned',teamId:data.team_id,events:0,status:'Pending'}]);setModal(false)}
 async function verifyParticipant(p:any){if(!demo){const {error}=await supabase.from('participants').update({verification_status:'verified'}).eq('id',p.dbId);if(error){setParticipantError(error.message);return}}setPeople(v=>v.map(x=>x.id===p.id?{...x,status:'Verified'}:x))}
 async function registerParticipant(eventId:string){if(!registering||!eventId)return;if(demo){setPeople(v=>v.map(x=>x.id===registering.id?{...x,events:x.events+1}:x));setRegistering(null);return}if(!setupFestival)return;const {error}=await supabase.from('registrations').insert({festival_id:setupFestival.id,event_id:eventId,participant_id:registering.dbId,status:'approved'});if(error){setParticipantError(error.code==='23505'?'This participant is already registered for that event.':error.message);setRegistering(null);return}setPeople(v=>v.map(x=>x.id===registering.id?{...x,events:x.events+1}:x));setRegistering(null);toast('Participant registered successfully')}
 async function addSetup(name:string,extra:string){if(demo){setSetupItems(v=>[...v,{id:Date.now(),name,code:extra,capacity:Number(extra)||null,color:'#ff5b22'}]);setSetupOpen(false);return}if(!setupFestival)return;const payload=setupTab==='teams'?{festival_id:setupFestival.id,name,code:extra.toUpperCase().replace(/\s+/g,'-'),color:'#ff5b22'}:setupTab==='venues'?{festival_id:setupFestival.id,name,capacity:Number(extra)||null}:{festival_id:setupFestival.id,name,description:extra};const {data,error}=await supabase.from(setupTab).insert(payload).select().single();if(error){setSetupError(error.message);return}setSetupItems(v=>[...v,data]);setSetupOpen(false)}
 if(active==='Setup') return <div className="module"><div className="setupHero"><div><small>FESTIVAL FOUNDATION</small><h2>Teams, categories & venues</h2><p>Configure the structure used by registrations, scheduling and results.</p></div><Settings/></div><div className="moduleBar"><div className="filters"><button className={setupTab==='teams'?'active':''} onClick={()=>setSetupTab('teams')}>Teams</button><button className={setupTab==='categories'?'active':''} onClick={()=>setSetupTab('categories')}>Categories</button><button className={setupTab==='venues'?'active':''} onClick={()=>setSetupTab('venues')}>Venues</button></div><button className="primary" onClick={()=>setSetupOpen(true)}><Plus/> Add {setupTab.slice(0,-1)}</button></div>{setupError&&<div className="authMessage">{setupError}</div>}<div className="setupGrid">{setupItems.map((x:any)=><article key={x.id}><span style={{background:x.color||'#ff5b22'}}>{x.name?.[0]}</span><div><h3>{x.name}</h3><p>{setupTab==='teams'?'Team code: '+x.code:setupTab==='venues'?(x.capacity?'Capacity: '+x.capacity:'No capacity limit'):(x.description||'No description')}</p></div><button className="mini">Edit</button></article>)}</div>{!setupItems.length&&<div className="emptySmall"><Settings/><b>No {setupTab} yet</b><span>Add the first {setupTab.slice(0,-1)} for your festival.</span></div>}{setupOpen&&<SetupForm type={setupTab} close={()=>setSetupOpen(false)} submit={addSetup}/>}</div>;
 if(active==='Participants') return <div className="module"><div className="moduleBar"><div className="filters"><button className="active">All <b>{people.length}</b></button><button>Verified</button><button>Pending</button></div><button className="primary" onClick={()=>setModal(true)}><Plus/> Add participant</button></div>{participantError&&<div className="authMessage">{participantError}</div>}<div className="metricRow"><article><span>Total participants</span><b>{people.length}</b><small>Across {participantTeams.length} teams</small></article><article><span>Verified entries</span><b>{people.filter(p=>p.status==='Verified').length}</b><small>Ready to compete</small></article><article><span>Registrations</span><b>{people.reduce((a,p)=>a+p.events,0)}</b><small>Individual & group</small></article></div>{people.length?<table><thead><tr><th>Participant</th><th>ID</th><th>Team</th><th>Events</th><th>Status</th><th/></tr></thead><tbody>{people.map(p=><tr key={p.id}><td><b>{p.name}</b></td><td>{p.id}</td><td><span className="teamTag">{p.team}</span></td><td>{p.events}</td><td><span className={'status '+(p.status==='Verified'?'completed':'upcoming')}>{p.status}</span></td><td><div className="rowActions"><button className="mini" onClick={()=>setRegistering(p)}>Register</button><button className="mini" disabled={p.status==='Verified'} onClick={()=>verifyParticipant(p)}>{p.status==='Verified'?'Verified':'Verify'}</button></div></td></tr>)}</tbody></table>:<div className="emptySmall"><Users/><b>No participants yet</b><span>Add your first participant and assign a team.</span></div>}{modal&&<QuickForm teams={participantTeams} close={()=>setModal(false)} submit={addParticipant}/>} {registering&&<RegistrationForm participant={registering} events={participantEvents} close={()=>setRegistering(null)} submit={registerParticipant}/>} {notice&&<div className="toast">{notice}</div>}</div>;
 if(active==='Schedule') return demo?<div className="module"><div className="moduleBar"><div className="dayTabs"><button className="active">DAY 01 <small>18 SEP</small></button><button>DAY 02 <small>19 SEP</small></button><button>DAY 03 <small>20 SEP</small></button></div><button className="primary"><Download/> Export</button></div><div className="scheduleGrid">{[['MAIN STAGE','#ff5b22',['09:30 · Mappilappattu','11:00 · Group Song','01:30 · Mime']],['ART HALL','#1d62f0',['09:15 · Arabic Calligraphy','10:45 · Watercolour','02:00 · Pencil Drawing']],['MEDIA LAB','#ffc928',['10:30 · Digital Poster','12:00 · Short Film','02:30 · Quiz']]].map((v:any)=><section key={v[0]}><header><i style={{background:v[1]}}/><b>{v[0]}</b></header>{v[2].map((n:string,i:number)=><article key={n} style={{borderLeftColor:v[1]}}><small>EVENT {i+1}</small><b>{n}</b><span>{[18,16,12][i]} entries</span></article>)}</section>)}</div></div>:<div className="module"><div className="moduleBar"><div className="dayTabs">{scheduleDays.map((d,i)=><button key={d} className={scheduleDate===d?'active':''} onClick={()=>setScheduleDate(d)}>DAY {String(i+1).padStart(2,'0')}<small>{new Date(d+'T00:00:00').toLocaleDateString('en',{day:'2-digit',month:'short'}).toUpperCase()}</small></button>)}</div><button className="primary" onClick={()=>toast('Schedule is ready for export')}><Download/> Export</button></div>{scheduleError&&<div className="authMessage">{scheduleError}</div>}{scheduleVenues.length?<div className="scheduleGrid liveSchedule">{scheduleVenues.map((venueName,i)=><section key={venueName}><header><i style={{background:['#ff5b22','#1d62f0','#ffc928','#9be83f'][i%4]}}/><b>{venueName.toUpperCase()}</b></header>{selectedScheduleEvents.filter(e=>(e.venues?.name||'Unassigned venue')===venueName).map((e:any)=><article key={e.id} style={{borderLeftColor:['#ff5b22','#1d62f0','#ffc928','#9be83f'][i%4]}}><small>{new Date(e.scheduled_start).toLocaleTimeString([],{hour:'2-digit',minute:'2-digit'})} · {e.categories?.name||'Uncategorised'}</small><b>{e.name}</b><span>{e.registrations?.[0]?.count||0} entries · {e.event_type}</span></article>)}</section>)}</div>:<div className="emptySmall"><Clock3/><b>No events scheduled for this day</b><span>Add or schedule events from the Events page.</span></div>}{scheduleEvents.some(e=>!e.scheduled_start)&&<div className="unscheduled"><b>{scheduleEvents.filter(e=>!e.scheduled_start).length} unscheduled events</b><span>Assign dates from Events to place them on the schedule.</span></div>}{notice&&<div className="toast">{notice}</div>}</div>;
 if(active==='Results') return <div className="module"><div className="moduleBar"><div className="filters"><button className="active">All results</button><button>Review</button><button>Published</button></div><button className="primary" onClick={()=>toast('Approved results published')}><Sparkles/> Publish approved</button></div><div className="resultHero"><div><small>TEAM CHAMPIONSHIP</small><h2>Aster leads Kala '26</h2><p>55 points ahead · 18 of 64 events completed</p></div><Trophy/><b>680<small>PTS</small></b></div><table><thead><tr><th>Event</th><th>First place</th><th>Second place</th><th>Third place</th><th>Action</th></tr></thead><tbody>{[['Mappilappattu','Amina · Aster','Rizwan · Nova','Nida · Solis'],['Arabic Calligraphy','Hiba · Nova','Adil · Orion','Nihal · Aster'],['Digital Poster','Fathima · Solis','Amal · Aster','Shamil · Nova']].map((r,i)=><tr key={r[0]}><td><b>{r[0]}</b><small>{i===2?'Awaiting review':'Published'}</small></td><td>{r[1]}</td><td>{r[2]}</td><td>{r[3]}</td><td><button className="mini" onClick={()=>toast(r[0]+' approved')}>{i===2?'Approve':'Scores'}</button></td></tr>)}</tbody></table>{notice&&<div className="toast">{notice}</div>}</div>;
 if(active==='Reports') return <div className="module"><div className="reportIntro"><div><small>REPORT CENTRE</small><h2>Ready-to-share festival documents</h2><p>Generate printable files from the latest approved festival data.</p></div><BarChart3/></div><div className="reportGrid">{[['Full result book','All ranks, points and standings','PDF'],['Participant registry','Participants with event entries','XLSX'],['Master schedule','Stage-wise three-day plan','PDF'],['Team score sheet','Championship point calculation','XLSX'],['Certificates','Winner and participant certificates','PDF'],['Audit summary','Approvals and publishing activity','CSV']].map(r=><article key={r[0]}><span><Download/></span><div><h3>{r[0]}</h3><p>{r[1]}</p></div><button onClick={()=>toast(r[0]+' prepared')}>{r[2]} <Download/></button></article>)}</div>{notice&&<div className="toast">{notice}</div>}</div>;
 return <div className="module settingsPage"><div className="settingsNav"><button className="active">Festival details</button><button>Users & roles</button><button>Scoring rules</button><button>Public portal</button></div><form onSubmit={e=>{e.preventDefault();toast('Festival settings saved')}}><small>GENERAL</small><h2>Festival details</h2><p>Used across dashboards, reports and public pages.</p><label>Festival name<input defaultValue="Kala '26"/></label><label>Tagline<input defaultValue="Celebrate Art. Organize Smart."/></label><div className="two"><label>Start date<input type="date" defaultValue="2026-09-18"/></label><label>End date<input type="date" defaultValue="2026-09-20"/></label></div><label>Host institution<input defaultValue="KalaTrack Demo Campus"/></label><div className="switchRow"><div><b>Public results portal</b><small>Allow public viewing of published results.</small></div><input type="checkbox" defaultChecked/></div><button className="primary">Save changes</button></form>{notice&&<div className="toast">{notice}</div>}</div>
}
function QuickForm({teams,close,submit}:{teams:any[],close:()=>void,submit:(name:string,id:string,teamId:string)=>void}){const [name,setName]=useState('');const [id,setId]=useState('');const [teamId,setTeamId]=useState('');return <div className="modalBackdrop"><form className="modal" onSubmit={e=>{e.preventDefault();submit(name,id,teamId)}}><button type="button" className="close" onClick={close}><X/></button><small>CREATE</small><h2>Add participant</h2><label>Full name<input required value={name} onChange={e=>setName(e.target.value)}/></label><label>Admission number<input required value={id} onChange={e=>setId(e.target.value)}/></label><label>Team<select value={teamId} onChange={e=>setTeamId(e.target.value)}><option value="">Unassigned</option>{teams.map(t=><option key={t.id} value={t.id}>{t.name}</option>)}</select></label>{!teams.length&&<div className="authMessage">No teams exist yet. Create teams from Setup, or save this participant as unassigned.</div>}<button className="primary">Save participant <ArrowRight/></button></form></div>}
function RegistrationForm({participant,events,close,submit}:{participant:any,events:any[],close:()=>void,submit:(eventId:string)=>void}){const [eventId,setEventId]=useState('');return <div className="modalBackdrop"><form className="modal" onSubmit={e=>{e.preventDefault();submit(eventId)}}><button type="button" className="close" onClick={close}><X/></button><small>EVENT ENTRY</small><h2>Register participant</h2><p><b>{participant.name}</b> · {participant.id} · {participant.team}</p><label>Choose event<select required value={eventId} onChange={e=>setEventId(e.target.value)}><option value="">Select an event</option>{events.map(ev=><option key={ev.id} value={ev.id}>{ev.name} · {ev.event_type}</option>)}</select></label>{!events.length&&<div className="authMessage">No events exist yet. Create an event before registering participants.</div>}<button className="primary" disabled={!events.length}>Register for event <ArrowRight/></button></form></div>}
function SetupForm({type,close,submit}:{type:'teams'|'categories'|'venues',close:()=>void,submit:(name:string,extra:string)=>void}){const [name,setName]=useState('');const [extra,setExtra]=useState('');const label=type==='teams'?'Team code':type==='venues'?'Capacity':'Description';return <div className="modalBackdrop"><form className="modal" onSubmit={e=>{e.preventDefault();submit(name,extra)}}><button type="button" className="close" onClick={close}><X/></button><small>FESTIVAL SETUP</small><h2>Add {type.slice(0,-1)}</h2><label>Name<input required value={name} onChange={e=>setName(e.target.value)} placeholder={type==='teams'?'Aster':type==='venues'?'Main Stage':'Fine Arts'}/></label><label>{label}<input required={type==='teams'} type={type==='venues'?'number':'text'} value={extra} onChange={e=>setExtra(e.target.value)}/></label><button className="primary">Save {type.slice(0,-1)} <ArrowRight/></button></form></div>}
function AuthScreen({back}:{back:()=>void}){const [signup,setSignup]=useState(false);const [busy,setBusy]=useState(false);const [message,setMessage]=useState('');async function submit(e:React.FormEvent<HTMLFormElement>){e.preventDefault();setBusy(true);setMessage('');const f=new FormData(e.currentTarget);const email=String(f.get('email'));const password=String(f.get('password'));const full_name=String(f.get('name')||'');const {error}=signup?await supabase.auth.signUp({email,password,options:{data:{full_name}}}):await supabase.auth.signInWithPassword({email,password});setBusy(false);setMessage(error?error.message:signup?'Account created. Check your email if confirmation is enabled.':'Signed in successfully.')}return <div className="authPage"><section className="authBrand"><Logo/><div><small>WELCOME TO KALATRACK</small><h1>Run the fest.<br/><em>Celebrate the art.</em></h1><p>One secure workspace for organizers, judges, teams and participants.</p></div><button onClick={back}>← Back to website</button></section><form className="authCard" onSubmit={submit}><span className="eyebrow">ORGANIZER ACCESS</span><h2>{signup?'Create your account':'Welcome back'}</h2><p>{signup?'Start setting up your first festival.':'Sign in to continue to your festival workspace.'}</p>{signup&&<label>Full name<input name="name" required placeholder="Muhammed Shinas"/></label>}<label>Email address<input name="email" type="email" required placeholder="you@example.com"/></label><label>Password<input name="password" type="password" required minLength={6} placeholder="Minimum 6 characters"/></label>{message&&<div className="authMessage">{message}</div>}<button className="primary" disabled={busy}>{busy?'Please wait...':signup?'Create account':'Sign in'} <ArrowRight/></button><button type="button" className="authSwitch" onClick={()=>{setSignup(!signup);setMessage('')}}>{signup?'Already have an account? Sign in':'New to KalaTrack? Create an account'}</button></form></div>}
function Onboarding({done}:{done:(festival:any)=>void}){const [busy,setBusy]=useState(false);const [error,setError]=useState('');async function create(e:React.FormEvent<HTMLFormElement>){e.preventDefault();setBusy(true);const f=new FormData(e.currentTarget);const {data:{user}}=await supabase.auth.getUser();if(!user)return;const name=String(f.get('name'));const {data,error}=await supabase.from('festivals').insert({name,slug:String(f.get('slug')).toLowerCase().replace(/[^a-z0-9-]/g,'-'),tagline:String(f.get('tagline')),host_name:String(f.get('host')),start_date:String(f.get('start')),end_date:String(f.get('end')),created_by:user.id,status:'active'}).select().single();setBusy(false);if(error)setError(error.message);else done(data)}return <div className="onboard"><div className="onboardHead"><Logo/><button onClick={()=>supabase.auth.signOut()}>Sign out</button></div><form onSubmit={create}><span className="eyebrow">FIRST FESTIVAL</span><h1>Let’s create your stage.</h1><p>You can change these details later in Settings.</p><label>Festival name<input name="name" required placeholder="Kala '26"/></label><label>Public URL slug<input name="slug" required placeholder="kala-26"/></label><label>Tagline<input name="tagline" placeholder="Celebrate Art. Organize Smart."/></label><label>Host institution<input name="host" required placeholder="Your college or organization"/></label><div className="two"><label>Start date<input name="start" type="date" required/></label><label>End date<input name="end" type="date" required/></label></div>{error&&<div className="authMessage">{error}</div>}<button className="primary" disabled={busy}>{busy?'Creating...':'Create festival'} <ArrowRight/></button></form></div>}
function App(){const [page,setPage]=useState<'landing'|'demo'|'auth'|'app'>('landing');const [session,setSession]=useState<any>(null);const [festival,setFestival]=useState<any>(null);const [loading,setLoading]=useState(true);useEffect(()=>{supabase.auth.getSession().then(({data})=>{setSession(data.session);setLoading(false)});const {data}=supabase.auth.onAuthStateChange((_e,s)=>{setSession(s);if(!s){setFestival(null);setPage('landing')}else setPage('app')});return()=>data.subscription.unsubscribe()},[]);useEffect(()=>{if(!session)return;supabase.from('festivals').select('*').order('created_at',{ascending:true}).limit(1).maybeSingle().then(({data})=>setFestival(data))},[session]);async function exit(){if(session)await supabase.auth.signOut();else{location.hash='';setPage('landing')}}if(loading)return <div className="splash"><Logo/><span>Preparing your stage...</span></div>;if(page==='demo')return <Dashboard exit={exit} demo/>;if(!session&&page==='auth')return <AuthScreen back={()=>setPage('landing')}/>;if(session&&!festival)return <Onboarding done={setFestival}/>;if(session&&festival)return <Dashboard exit={exit} festival={festival}/>;return <Landing demo={()=>setPage('demo')} login={()=>setPage('auth')}/>}
createRoot(document.getElementById('root')!).render(<App/>);
